name: Scheduled task

on:
  # schedule:
  #   - cron: "0/10 * * * *"
  workflow_dispatch:

jobs:
  insert-new-documents-to-databases:
    runs-on: ubuntu-latest
    env:
      MONGODB_PASSWORD: ${{ secrets.MONGODB_PASSWORD }}
    steps:
      - name: checkout repo content
        uses: actions/checkout@v2
      - uses: actions/cache@v2
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-
      - name: install Python dependencies
        run: pip install -r requirements.txt
      - name: add new documents to mongodb
        run: python scheduled_fetch.py

  wake-up-dyno:
    runs-on: ubuntu-latest
    steps:
      - name: access website
        run: curl https://reaktor-preassignment-dev-2022.herokuapp.com