name: Automatic fetching data

on:
  schedule:
    - cron: "0/15 * * * *"
  workflow_dispatch:

jobs:
  insert-new-documents:
    runs-on: ubuntu-latest
    env:
      MONGODB_PASSWORD: ${{ secrets.MONGODB_PASSWORD }}
    steps:
      - name: checkout repo content
        uses: actions/checkout@v2
      - uses: actions/cache@v2
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-
      - run: pip install -r requirements.txt
      - name: add new documents to mongodb
        run: python scheduled_fetch.py
